//
//  LuaOpenGLES.m
//  LuaIOS
//
//  Created by tearsofphoenix tearsofphoenix on 6/19/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import "LuaOpenGLES.h"
#import "luasdk_utilities.h"
#import "LuaObjCAuxiliary.h"
#import "lauxlib.h"

static const LuaSDKConst __luaObjCOpenGLESConstants[] = 
{
    {"EAGL_MAJOR_VERSION", EAGL_MAJOR_VERSION},
    {"EAGL_MINOR_VERSION", EAGL_MINOR_VERSION},
    {"GL_ACTIVE_ATTRIBUTES", GL_ACTIVE_ATTRIBUTES},
    {"GL_ACTIVE_ATTRIBUTE_MAX_LENGTH", GL_ACTIVE_ATTRIBUTE_MAX_LENGTH},
    {"GL_ACTIVE_PROGRAM_EXT", GL_ACTIVE_PROGRAM_EXT},
    {"GL_ACTIVE_TEXTURE", GL_ACTIVE_TEXTURE},
    {"GL_ACTIVE_UNIFORMS", GL_ACTIVE_UNIFORMS},
    {"GL_ACTIVE_UNIFORM_MAX_LENGTH", GL_ACTIVE_UNIFORM_MAX_LENGTH},
    {"GL_ALIASED_LINE_WIDTH_RANGE", GL_ALIASED_LINE_WIDTH_RANGE},
    {"GL_ALIASED_POINT_SIZE_RANGE", GL_ALIASED_POINT_SIZE_RANGE},
    {"GL_ALL_SHADER_BITS_EXT", GL_ALL_SHADER_BITS_EXT},
    {"GL_ALPHA", GL_ALPHA},
    {"GL_ALPHA_BITS", GL_ALPHA_BITS},
    {"GL_ADD", GL_ADD},
    {"GL_ADD_SIGNED", GL_ADD_SIGNED},
    {"GL_ALPHA_SCALE", GL_ALPHA_SCALE},
    {"GL_ALPHA_TEST", GL_ALPHA_TEST},
    {"GL_ALPHA_TEST_FUNC", GL_ALPHA_TEST_FUNC},
    {"GL_ALPHA_TEST_REF", GL_ALPHA_TEST_REF},
    {"GL_ALWAYS", GL_ALWAYS},
    {"GL_AMBIENT", GL_AMBIENT},
    {"GL_AMBIENT_AND_DIFFUSE", GL_AMBIENT_AND_DIFFUSE},
    {"GL_AND", GL_AND},
    {"GL_AND_INVERTED", GL_AND_INVERTED},
    {"GL_AND_REVERSE", GL_AND_REVERSE},
    {"GL_ANY_SAMPLES_PASSED_CONSERVATIVE_EXT", GL_ANY_SAMPLES_PASSED_CONSERVATIVE_EXT},
    {"GL_ANY_SAMPLES_PASSED_EXT", GL_ANY_SAMPLES_PASSED_EXT},
    {"GL_APPLE_framebuffer_multisample", GL_APPLE_framebuffer_multisample},
    {"GL_APPLE_rgb_422", GL_APPLE_rgb_422},
    {"GL_APPLE_texture_2D_limited_npot", GL_APPLE_texture_2D_limited_npot},
    {"GL_APPLE_texture_format_BGRA8888", GL_APPLE_texture_format_BGRA8888},
    {"GL_APPLE_texture_max_level", GL_APPLE_texture_max_level},
    {"GL_ARRAY_BUFFER", GL_ARRAY_BUFFER},
    {"GL_ARRAY_BUFFER_BINDING", GL_ARRAY_BUFFER_BINDING},
    {"GL_ATTACHED_SHADERS", GL_ATTACHED_SHADERS},
    {"GL_BACK", GL_BACK},
    {"GL_BGRA", GL_BGRA},
    {"GL_BGRA_EXT", GL_BGRA_EXT},
    {"GL_BGRA_IMG", GL_BGRA_IMG},
    {"GL_BLEND", GL_BLEND},
    {"GL_BLEND_COLOR", GL_BLEND_COLOR},
    {"GL_BLEND_DST", GL_BLEND_DST},
    {"GL_BLEND_DST_ALPHA", GL_BLEND_DST_ALPHA},
    {"GL_BLEND_DST_ALPHA_OES", GL_BLEND_DST_ALPHA_OES},
    {"GL_BLEND_DST_RGB", GL_BLEND_DST_RGB},
    {"GL_BLEND_DST_RGB_OES", GL_BLEND_DST_RGB_OES},
    {"GL_BLEND_EQUATION", GL_BLEND_EQUATION},
    {"GL_BLEND_EQUATION_ALPHA", GL_BLEND_EQUATION_ALPHA},
    {"GL_BLEND_EQUATION_ALPHA_OES", GL_BLEND_EQUATION_ALPHA_OES},
    {"GL_BLEND_EQUATION_OES", GL_BLEND_EQUATION_OES},
    {"GL_BLEND_EQUATION_RGB", GL_BLEND_EQUATION_RGB},
    {"GL_BLEND_EQUATION_RGB_OES", GL_BLEND_EQUATION_RGB_OES},
    {"GL_BLEND_SRC", GL_BLEND_SRC},
    {"GL_BLEND_SRC_ALPHA", GL_BLEND_SRC_ALPHA},
    {"GL_BLEND_SRC_ALPHA_OES", GL_BLEND_SRC_ALPHA_OES},
    {"GL_BLEND_SRC_RGB", GL_BLEND_SRC_RGB},
    {"GL_BLEND_SRC_RGB_OES", GL_BLEND_SRC_RGB_OES},
    {"GL_BLUE_BITS", GL_BLUE_BITS},
    {"GL_BOOL", GL_BOOL},
    {"GL_BOOL_VEC2", GL_BOOL_VEC2},
    {"GL_BOOL_VEC3", GL_BOOL_VEC3},
    {"GL_BOOL_VEC4", GL_BOOL_VEC4},
    {"GL_BUFFER_ACCESS_OES", GL_BUFFER_ACCESS_OES},
    {"GL_BUFFER_MAPPED_OES", GL_BUFFER_MAPPED_OES},
    {"GL_BUFFER_MAP_POINTER_OES", GL_BUFFER_MAP_POINTER_OES},
    {"GL_BUFFER_OBJECT_EXT", GL_BUFFER_OBJECT_EXT},
    {"GL_BUFFER_SIZE", GL_BUFFER_SIZE},
    {"GL_BUFFER_USAGE", GL_BUFFER_USAGE},
    {"GL_BYTE", GL_BYTE},
    {"GL_CCW", GL_CCW},
    {"GL_CLAMP_TO_EDGE", GL_CLAMP_TO_EDGE},
    {"GL_CLEAR", GL_CLEAR},
    {"GL_CLIENT_ACTIVE_TEXTURE", GL_CLIENT_ACTIVE_TEXTURE},
    {"GL_CLIP_PLANE0", GL_CLIP_PLANE0},
    {"GL_CLIP_PLANE1", GL_CLIP_PLANE1},
    {"GL_CLIP_PLANE2", GL_CLIP_PLANE2},
    {"GL_CLIP_PLANE3", GL_CLIP_PLANE3},
    {"GL_CLIP_PLANE4", GL_CLIP_PLANE4},
    {"GL_CLIP_PLANE5", GL_CLIP_PLANE5},
    {"GL_COLOR_ARRAY", GL_COLOR_ARRAY},
    {"GL_COLOR_ARRAY_BUFFER_BINDING", GL_COLOR_ARRAY_BUFFER_BINDING},
    {"GL_COLOR_ARRAY_POINTER", GL_COLOR_ARRAY_POINTER},
    {"GL_COLOR_ARRAY_SIZE", GL_COLOR_ARRAY_SIZE},
    {"GL_COLOR_ARRAY_STRIDE", GL_COLOR_ARRAY_STRIDE},
    {"GL_COLOR_ARRAY_TYPE", GL_COLOR_ARRAY_TYPE},
    {"GL_COLOR_ATTACHMENT0", GL_COLOR_ATTACHMENT0},
    {"GL_COLOR_ATTACHMENT0_OES", GL_COLOR_ATTACHMENT0_OES},
    {"GL_COLOR_BUFFER_BIT", GL_COLOR_BUFFER_BIT},
    {"GL_COLOR_CLEAR_VALUE", GL_COLOR_CLEAR_VALUE},
    {"GL_COLOR_EXT", GL_COLOR_EXT},
    {"GL_COLOR_LOGIC_OP", GL_COLOR_LOGIC_OP},
    {"GL_COLOR_MATERIAL", GL_COLOR_MATERIAL},
    {"GL_COLOR_WRITEMASK", GL_COLOR_WRITEMASK},
    {"GL_COMBINE", GL_COMBINE},
    {"GL_COMBINE_ALPHA", GL_COMBINE_ALPHA},
    {"GL_COMBINE_RGB", GL_COMBINE_RGB},
    {"GL_COMPARE_REF_TO_TEXTURE_EXT", GL_COMPARE_REF_TO_TEXTURE_EXT},
    {"GL_COMPILE_STATUS", GL_COMPILE_STATUS},
    {"GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG", GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG},
    {"GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG", GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG},
    {"GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG", GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG},
    {"GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG", GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG},
    {"GL_COMPRESSED_TEXTURE_FORMATS", GL_COMPRESSED_TEXTURE_FORMATS},
    {"GL_CONSTANT", GL_CONSTANT},
    {"GL_CONSTANT_ALPHA", GL_CONSTANT_ALPHA},
    {"GL_CONSTANT_ATTENUATION", GL_CONSTANT_ATTENUATION},
    {"GL_CONSTANT_COLOR", GL_CONSTANT_COLOR},
    {"GL_COORD_REPLACE_OES", GL_COORD_REPLACE_OES},
    {"GL_COPY", GL_COPY},
    {"GL_COPY_INVERTED", GL_COPY_INVERTED},
    {"GL_CULL_FACE", GL_CULL_FACE},
    {"GL_CULL_FACE_MODE", GL_CULL_FACE_MODE},
    {"GL_CURRENT_COLOR", GL_CURRENT_COLOR},
    {"GL_CURRENT_NORMAL", GL_CURRENT_NORMAL},
    {"GL_CURRENT_PALETTE_MATRIX_OES", GL_CURRENT_PALETTE_MATRIX_OES},
    {"GL_CURRENT_PROGRAM", GL_CURRENT_PROGRAM},
    {"GL_CURRENT_QUERY_EXT", GL_CURRENT_QUERY_EXT},
    {"GL_CURRENT_TEXTURE_COORDS", GL_CURRENT_TEXTURE_COORDS},
    {"GL_CURRENT_VERTEX_ATTRIB", GL_CURRENT_VERTEX_ATTRIB},
    {"GL_CW", GL_CW},
    {"GL_DECAL", GL_DECAL},
    {"GL_DECR", GL_DECR},
    {"GL_DECR_WRAP", GL_DECR_WRAP},
    {"GL_DECR_WRAP_OES", GL_DECR_WRAP_OES},
    {"GL_DELETE_STATUS", GL_DELETE_STATUS},
    {"GL_DEPTH24_STENCIL8_OES", GL_DEPTH24_STENCIL8_OES},
    {"GL_DEPTH_ATTACHMENT", GL_DEPTH_ATTACHMENT},
    {"GL_DEPTH_ATTACHMENT_OES", GL_DEPTH_ATTACHMENT_OES},
    {"GL_DEPTH_BITS", GL_DEPTH_BITS},
    {"GL_DEPTH_BUFFER_BIT", GL_DEPTH_BUFFER_BIT},
    {"GL_DEPTH_CLEAR_VALUE", GL_DEPTH_CLEAR_VALUE},
    {"GL_DEPTH_COMPONENT", GL_DEPTH_COMPONENT},
    {"GL_DEPTH_COMPONENT16", GL_DEPTH_COMPONENT16},
    {"GL_DEPTH_COMPONENT16_OES", GL_DEPTH_COMPONENT16_OES},
    {"GL_DEPTH_COMPONENT24_OES", GL_DEPTH_COMPONENT24_OES},
    {"GL_DEPTH_EXT", GL_DEPTH_EXT},
    {"GL_DEPTH_FUNC", GL_DEPTH_FUNC},
    {"GL_DEPTH_RANGE", GL_DEPTH_RANGE},
    {"GL_DEPTH_STENCIL_OES", GL_DEPTH_STENCIL_OES},
    {"GL_DEPTH_TEST", GL_DEPTH_TEST},
    {"GL_DEPTH_WRITEMASK", GL_DEPTH_WRITEMASK},
    {"GL_DIFFUSE", GL_DIFFUSE},
    {"GL_DITHER", GL_DITHER},
    {"GL_DONT_CARE", GL_DONT_CARE},
    {"GL_DOT3_RGB", GL_DOT3_RGB},
    {"GL_DOT3_RGBA", GL_DOT3_RGBA},
    {"GL_DRAW_FRAMEBUFFER_APPLE", GL_DRAW_FRAMEBUFFER_APPLE},
    {"GL_DRAW_FRAMEBUFFER_BINDING_APPLE", GL_DRAW_FRAMEBUFFER_BINDING_APPLE},
    {"GL_DST_ALPHA", GL_DST_ALPHA},
    {"GL_DST_COLOR", GL_DST_COLOR},
    {"GL_DYNAMIC_DRAW", GL_DYNAMIC_DRAW},
    {"GL_ELEMENT_ARRAY_BUFFER", GL_ELEMENT_ARRAY_BUFFER},
    {"GL_ELEMENT_ARRAY_BUFFER_BINDING", GL_ELEMENT_ARRAY_BUFFER_BINDING},
    {"GL_EMISSION", GL_EMISSION},
    {"GL_EQUAL", GL_EQUAL},
    {"GL_EQUIV", GL_EQUIV},
    {"GL_ES_VERSION_2_0", GL_ES_VERSION_2_0},
    {"GL_EXP", GL_EXP},
    {"GL_EXP2", GL_EXP2},
    {"GL_EXTENSIONS", GL_EXTENSIONS},
    {"GL_EXT_blend_minmax", GL_EXT_blend_minmax},
    {"GL_EXT_color_buffer_half_float", GL_EXT_color_buffer_half_float},
    {"GL_EXT_debug_label", GL_EXT_debug_label},
    {"GL_EXT_debug_marker", GL_EXT_debug_marker},
    {"GL_EXT_discard_framebuffer", GL_EXT_discard_framebuffer},
    {"GL_EXT_occlusion_query_boolean", GL_EXT_occlusion_query_boolean},
    {"GL_EXT_read_format_bgra", GL_EXT_read_format_bgra},
    {"GL_EXT_separate_shader_objects", GL_EXT_separate_shader_objects},
    {"GL_EXT_shader_texture_lod", GL_EXT_shader_texture_lod},
    {"GL_EXT_shadow_samplers", GL_EXT_shadow_samplers},
    {"GL_EXT_texture_filter_anisotropic", GL_EXT_texture_filter_anisotropic},
    {"GL_EXT_texture_lod_bias", GL_EXT_texture_lod_bias},
    {"GL_EXT_texture_rg", GL_EXT_texture_rg},
    {"GL_FALSE", GL_FALSE},
    {"GL_FASTEST", GL_FASTEST},
    {"GL_FIXED", GL_FIXED},
    {"GL_FLAT", GL_FLAT},
    {"GL_FLOAT", GL_FLOAT},
    {"GL_FLOAT_MAT2", GL_FLOAT_MAT2},
    {"GL_FLOAT_MAT3", GL_FLOAT_MAT3},
    {"GL_FLOAT_MAT4", GL_FLOAT_MAT4},
    {"GL_FLOAT_VEC2", GL_FLOAT_VEC2},
    {"GL_FLOAT_VEC3", GL_FLOAT_VEC3},
    {"GL_FLOAT_VEC4", GL_FLOAT_VEC4},
    {"GL_FOG", GL_FOG},
    {"GL_FOG_COLOR", GL_FOG_COLOR},
    {"GL_FOG_DENSITY", GL_FOG_DENSITY},
    {"GL_FOG_END", GL_FOG_END},
    {"GL_FOG_HINT", GL_FOG_HINT},
    {"GL_FOG_MODE", GL_FOG_MODE},
    {"GL_FOG_START", GL_FOG_START},
    {"GL_FRAGMENT_SHADER", GL_FRAGMENT_SHADER},
    {"GL_FRAGMENT_SHADER_BIT_EXT", GL_FRAGMENT_SHADER_BIT_EXT},
    {"GL_FRAGMENT_SHADER_DERIVATIVE_HINT_OES", GL_FRAGMENT_SHADER_DERIVATIVE_HINT_OES},
    {"GL_FRAMEBUFFER", GL_FRAMEBUFFER},
    {"GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT", GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT},
    {"GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME", GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME},
    {"GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES", GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES},
    {"GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE", GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE},
    {"GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES", GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES},
    {"GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE", GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE},
    {"GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES", GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES},
    {"GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL", GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL},
    {"GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES", GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES},
    {"GL_FRAMEBUFFER_BINDING", GL_FRAMEBUFFER_BINDING},
    {"GL_FRAMEBUFFER_BINDING_OES", GL_FRAMEBUFFER_BINDING_OES},
    {"GL_FRAMEBUFFER_COMPLETE", GL_FRAMEBUFFER_COMPLETE},
    {"GL_FRAMEBUFFER_COMPLETE_OES", GL_FRAMEBUFFER_COMPLETE_OES},
    {"GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT", GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT},
    {"GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES", GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES},
    {"GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS", GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS},
    {"GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES", GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES},
    {"GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES", GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES},
    {"GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT", GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT},
    {"GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES", GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES},
    {"GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE", GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE},
    {"GL_FRAMEBUFFER_OES", GL_FRAMEBUFFER_OES},
    {"GL_FRAMEBUFFER_UNSUPPORTED", GL_FRAMEBUFFER_UNSUPPORTED},
    {"GL_FRAMEBUFFER_UNSUPPORTED_OES", GL_FRAMEBUFFER_UNSUPPORTED_OES},
    {"GL_FRONT", GL_FRONT},
    {"GL_FRONT_AND_BACK", GL_FRONT_AND_BACK},
    {"GL_FRONT_FACE", GL_FRONT_FACE},
    {"GL_FUNC_ADD", GL_FUNC_ADD},
    {"GL_FUNC_ADD_OES", GL_FUNC_ADD_OES},
    {"GL_FUNC_REVERSE_SUBTRACT", GL_FUNC_REVERSE_SUBTRACT},
    {"GL_FUNC_REVERSE_SUBTRACT_OES", GL_FUNC_REVERSE_SUBTRACT_OES},
    {"GL_FUNC_SUBTRACT", GL_FUNC_SUBTRACT},
    {"GL_FUNC_SUBTRACT_OES", GL_FUNC_SUBTRACT_OES},
    {"GL_GENERATE_MIPMAP", GL_GENERATE_MIPMAP},
    {"GL_GENERATE_MIPMAP_HINT", GL_GENERATE_MIPMAP_HINT},
    {"GL_GEQUAL", GL_GEQUAL},
    {"GL_GREATER", GL_GREATER},
    {"GL_GREEN_BITS", GL_GREEN_BITS},
    {"GL_HALF_FLOAT_OES", GL_HALF_FLOAT_OES},
    {"GL_HIGH_FLOAT", GL_HIGH_FLOAT},
    {"GL_HIGH_INT", GL_HIGH_INT},
    {"GL_IMG_read_format", GL_IMG_read_format},
    {"GL_IMG_texture_compression_pvrtc", GL_IMG_texture_compression_pvrtc},
    {"GL_IMPLEMENTATION_COLOR_READ_FORMAT", GL_IMPLEMENTATION_COLOR_READ_FORMAT},
    {"GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES", GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES},
    {"GL_IMPLEMENTATION_COLOR_READ_TYPE", GL_IMPLEMENTATION_COLOR_READ_TYPE},
    {"GL_IMPLEMENTATION_COLOR_READ_TYPE_OES", GL_IMPLEMENTATION_COLOR_READ_TYPE_OES},
    {"GL_INCR", GL_INCR},
    {"GL_INCR_WRAP", GL_INCR_WRAP},
    {"GL_INCR_WRAP_OES", GL_INCR_WRAP_OES},
    {"GL_INFO_LOG_LENGTH", GL_INFO_LOG_LENGTH},
    {"GL_INT", GL_INT},
    {"GL_INTERPOLATE", GL_INTERPOLATE},
    {"GL_INT_VEC2", GL_INT_VEC2},
    {"GL_INT_VEC3", GL_INT_VEC3},
    {"GL_INT_VEC4", GL_INT_VEC4},
    {"GL_INVALID_ENUM", GL_INVALID_ENUM},
    {"GL_INVALID_FRAMEBUFFER_OPERATION", GL_INVALID_FRAMEBUFFER_OPERATION},
    {"GL_INVALID_FRAMEBUFFER_OPERATION_OES", GL_INVALID_FRAMEBUFFER_OPERATION_OES},
    {"GL_INVALID_OPERATION", GL_INVALID_OPERATION},
    {"GL_INVALID_VALUE", GL_INVALID_VALUE},
    {"GL_INVERT", GL_INVERT},
    {"GL_KEEP", GL_KEEP},
    {"GL_LEQUAL", GL_LEQUAL},
    {"GL_LESS", GL_LESS},
    {"GL_LIGHT0", GL_LIGHT0},
    {"GL_LIGHT1", GL_LIGHT1},
    {"GL_LIGHT2", GL_LIGHT2},
    {"GL_LIGHT3", GL_LIGHT3},
    {"GL_LIGHT4", GL_LIGHT4},
    {"GL_LIGHT5", GL_LIGHT5},
    {"GL_LIGHT6", GL_LIGHT6},
    {"GL_LIGHT7", GL_LIGHT7},
    {"GL_LIGHTING", GL_LIGHTING},
    {"GL_LIGHT_MODEL_AMBIENT", GL_LIGHT_MODEL_AMBIENT},
    {"GL_LIGHT_MODEL_TWO_SIDE", GL_LIGHT_MODEL_TWO_SIDE},
    {"GL_LINEAR", GL_LINEAR},
    {"GL_LINEAR_ATTENUATION", GL_LINEAR_ATTENUATION},
    {"GL_LINEAR_MIPMAP_LINEAR", GL_LINEAR_MIPMAP_LINEAR},
    {"GL_LINEAR_MIPMAP_NEAREST", GL_LINEAR_MIPMAP_NEAREST},
    {"GL_LINES", GL_LINES},
    {"GL_LINE_LOOP", GL_LINE_LOOP},
    {"GL_LINE_SMOOTH", GL_LINE_SMOOTH},
    {"GL_LINE_SMOOTH_HINT", GL_LINE_SMOOTH_HINT},
    {"GL_LINE_STRIP", GL_LINE_STRIP},
    {"GL_LINE_WIDTH", GL_LINE_WIDTH},
    {"GL_LINK_STATUS", GL_LINK_STATUS},
    {"GL_LOGIC_OP_MODE", GL_LOGIC_OP_MODE},
    {"GL_LOW_FLOAT", GL_LOW_FLOAT},
    {"GL_LOW_INT", GL_LOW_INT},
    {"GL_LUMINANCE", GL_LUMINANCE},
    {"GL_LUMINANCE_ALPHA", GL_LUMINANCE_ALPHA},
    {"GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES", GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES},
    {"GL_MATRIX_INDEX_ARRAY_OES", GL_MATRIX_INDEX_ARRAY_OES},
    {"GL_MATRIX_INDEX_ARRAY_POINTER_OES", GL_MATRIX_INDEX_ARRAY_POINTER_OES},
    {"GL_MATRIX_INDEX_ARRAY_SIZE_OES", GL_MATRIX_INDEX_ARRAY_SIZE_OES},
    {"GL_MATRIX_INDEX_ARRAY_STRIDE_OES", GL_MATRIX_INDEX_ARRAY_STRIDE_OES},
    {"GL_MATRIX_INDEX_ARRAY_TYPE_OES", GL_MATRIX_INDEX_ARRAY_TYPE_OES},
    {"GL_MATRIX_MODE", GL_MATRIX_MODE},
    {"GL_MATRIX_PALETTE_OES", GL_MATRIX_PALETTE_OES},
    {"GL_MAX_CLIP_PLANES", GL_MAX_CLIP_PLANES},
    {"GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS", GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS},
    {"GL_MAX_CUBE_MAP_TEXTURE_SIZE", GL_MAX_CUBE_MAP_TEXTURE_SIZE},
    {"GL_MAX_EXT", GL_MAX_EXT},
    {"GL_MAX_FRAGMENT_UNIFORM_VECTORS", GL_MAX_FRAGMENT_UNIFORM_VECTORS},
    {"GL_MAX_LIGHTS", GL_MAX_LIGHTS},
    {"GL_MAX_MODELVIEW_STACK_DEPTH", GL_MAX_MODELVIEW_STACK_DEPTH},
    {"GL_MAX_PALETTE_MATRICES_OES", GL_MAX_PALETTE_MATRICES_OES},
    {"GL_MAX_PROJECTION_STACK_DEPTH", GL_MAX_PROJECTION_STACK_DEPTH},
    {"GL_MAX_RENDERBUFFER_SIZE", GL_MAX_RENDERBUFFER_SIZE},
    {"GL_MAX_RENDERBUFFER_SIZE_OES", GL_MAX_RENDERBUFFER_SIZE_OES},
    {"GL_MAX_SAMPLES_APPLE", GL_MAX_SAMPLES_APPLE},
    {"GL_MAX_TEXTURE_IMAGE_UNITS", GL_MAX_TEXTURE_IMAGE_UNITS},
    {"GL_MAX_TEXTURE_LOD_BIAS_EXT", GL_MAX_TEXTURE_LOD_BIAS_EXT},
    {"GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT", GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT},
    {"GL_MAX_TEXTURE_SIZE", GL_MAX_TEXTURE_SIZE},
    {"GL_MAX_TEXTURE_STACK_DEPTH", GL_MAX_TEXTURE_STACK_DEPTH},
    {"GL_MAX_TEXTURE_UNITS", GL_MAX_TEXTURE_UNITS},
    {"GL_MAX_VARYING_VECTORS", GL_MAX_VARYING_VECTORS},
    {"GL_MAX_VERTEX_ATTRIBS", GL_MAX_VERTEX_ATTRIBS},
    {"GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS", GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS},
    {"GL_MAX_VERTEX_UNIFORM_VECTORS", GL_MAX_VERTEX_UNIFORM_VECTORS},
    {"GL_MAX_VERTEX_UNITS_OES", GL_MAX_VERTEX_UNITS_OES},
    {"GL_MAX_VIEWPORT_DIMS", GL_MAX_VIEWPORT_DIMS},
    {"GL_MEDIUM_FLOAT", GL_MEDIUM_FLOAT},
    {"GL_MEDIUM_INT", GL_MEDIUM_INT},
    {"GL_MIN_EXT", GL_MIN_EXT},
    {"GL_MIRRORED_REPEAT", GL_MIRRORED_REPEAT},
    {"GL_MIRRORED_REPEAT_OES", GL_MIRRORED_REPEAT_OES},
    {"GL_MODELVIEW", GL_MODELVIEW},
    {"GL_MODELVIEW_MATRIX", GL_MODELVIEW_MATRIX},
    {"GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES", GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES},
    {"GL_MODELVIEW_STACK_DEPTH", GL_MODELVIEW_STACK_DEPTH},
    {"GL_MODULATE", GL_MODULATE},
    {"GL_MULTISAMPLE", GL_MULTISAMPLE},
    {"GL_NAND", GL_NAND},
    {"GL_NEAREST", GL_NEAREST},
    {"GL_NEAREST_MIPMAP_LINEAR", GL_NEAREST_MIPMAP_LINEAR},
    {"GL_NEAREST_MIPMAP_NEAREST", GL_NEAREST_MIPMAP_NEAREST},
    {"GL_NEVER", GL_NEVER},
    {"GL_NICEST", GL_NICEST},
    {"GL_NONE", GL_NONE},
    {"GL_NOOP", GL_NOOP},
    {"GL_NOR", GL_NOR},
    {"GL_NORMALIZE", GL_NORMALIZE},
    {"GL_NORMAL_ARRAY", GL_NORMAL_ARRAY},
    {"GL_NORMAL_ARRAY_BUFFER_BINDING", GL_NORMAL_ARRAY_BUFFER_BINDING},
    {"GL_NORMAL_ARRAY_POINTER", GL_NORMAL_ARRAY_POINTER},
    {"GL_NORMAL_ARRAY_STRIDE", GL_NORMAL_ARRAY_STRIDE},
    {"GL_NORMAL_ARRAY_TYPE", GL_NORMAL_ARRAY_TYPE},
    {"GL_NOTEQUAL", GL_NOTEQUAL},
    {"GL_NO_ERROR", GL_NO_ERROR},
    {"GL_NUM_COMPRESSED_TEXTURE_FORMATS", GL_NUM_COMPRESSED_TEXTURE_FORMATS},
    {"GL_NUM_SHADER_BINARY_FORMATS", GL_NUM_SHADER_BINARY_FORMATS},
    {"GL_OES_VERSION_1_0", GL_OES_VERSION_1_0},
    {"GL_OES_VERSION_1_1", GL_OES_VERSION_1_1},
    {"GL_OES_blend_equation_separate", GL_OES_blend_equation_separate},
    {"GL_OES_blend_func_separate", GL_OES_blend_func_separate},
    {"GL_OES_blend_subtract", GL_OES_blend_subtract},
    {"GL_OES_byte_coordinates", GL_OES_byte_coordinates},
    {"GL_OES_compressed_paletted_texture", GL_OES_compressed_paletted_texture},
    {"GL_OES_depth24", GL_OES_depth24},
    {"GL_OES_depth_texture", GL_OES_depth_texture},
    {"GL_OES_draw_texture", GL_OES_draw_texture},
    {"GL_OES_element_index_uint", GL_OES_element_index_uint},
    {"GL_OES_fbo_render_mipmap", GL_OES_fbo_render_mipmap},
    {"GL_OES_fixed_point", GL_OES_fixed_point},
    {"GL_OES_framebuffer_object", GL_OES_framebuffer_object},
    {"GL_OES_mapbuffer", GL_OES_mapbuffer},
    {"GL_OES_matrix_get", GL_OES_matrix_get},
    {"GL_OES_matrix_palette", GL_OES_matrix_palette},
    {"GL_OES_packed_depth_stencil", GL_OES_packed_depth_stencil},
    {"GL_OES_point_size_array", GL_OES_point_size_array},
    {"GL_OES_point_sprite", GL_OES_point_sprite},
    {"GL_OES_read_format", GL_OES_read_format},
    {"GL_OES_rgb8_rgba8", GL_OES_rgb8_rgba8},
    {"GL_OES_single_precision", GL_OES_single_precision},
    {"GL_OES_standard_derivatives", GL_OES_standard_derivatives},
    {"GL_OES_stencil8", GL_OES_stencil8},
    {"GL_OES_stencil_wrap", GL_OES_stencil_wrap},
    {"GL_OES_texture_float", GL_OES_texture_float},
    {"GL_OES_texture_half_float", GL_OES_texture_half_float},
    {"GL_OES_texture_mirrored_repeat", GL_OES_texture_mirrored_repeat},
    {"GL_OES_vertex_array_object", GL_OES_vertex_array_object},
    {"GL_ONE", GL_ONE},
    {"GL_ONE_MINUS_CONSTANT_ALPHA", GL_ONE_MINUS_CONSTANT_ALPHA},
    {"GL_ONE_MINUS_CONSTANT_COLOR", GL_ONE_MINUS_CONSTANT_COLOR},
    {"GL_ONE_MINUS_DST_ALPHA", GL_ONE_MINUS_DST_ALPHA},
    {"GL_ONE_MINUS_DST_COLOR", GL_ONE_MINUS_DST_COLOR},
    {"GL_ONE_MINUS_SRC_ALPHA", GL_ONE_MINUS_SRC_ALPHA},
    {"GL_ONE_MINUS_SRC_COLOR", GL_ONE_MINUS_SRC_COLOR},
    {"GL_OPERAND0_ALPHA", GL_OPERAND0_ALPHA},
    {"GL_OPERAND0_RGB", GL_OPERAND0_RGB},
    {"GL_OPERAND1_ALPHA", GL_OPERAND1_ALPHA},
    {"GL_OPERAND1_RGB", GL_OPERAND1_RGB},
    {"GL_OPERAND2_ALPHA", GL_OPERAND2_ALPHA},
    {"GL_OPERAND2_RGB", GL_OPERAND2_RGB},
    {"GL_OR", GL_OR},
    {"GL_OR_INVERTED", GL_OR_INVERTED},
    {"GL_OR_REVERSE", GL_OR_REVERSE},
    {"GL_OUT_OF_MEMORY", GL_OUT_OF_MEMORY},
    {"GL_PACK_ALIGNMENT", GL_PACK_ALIGNMENT},
    {"GL_PALETTE4_R5_G6_B5_OES", GL_PALETTE4_R5_G6_B5_OES},
    {"GL_PALETTE4_RGB5_A1_OES", GL_PALETTE4_RGB5_A1_OES},
    {"GL_PALETTE4_RGB8_OES", GL_PALETTE4_RGB8_OES},
    {"GL_PALETTE4_RGBA4_OES", GL_PALETTE4_RGBA4_OES},
    {"GL_PALETTE4_RGBA8_OES", GL_PALETTE4_RGBA8_OES},
    {"GL_PALETTE8_R5_G6_B5_OES", GL_PALETTE8_R5_G6_B5_OES},
    {"GL_PALETTE8_RGB5_A1_OES", GL_PALETTE8_RGB5_A1_OES},
    {"GL_PALETTE8_RGB8_OES", GL_PALETTE8_RGB8_OES},
    {"GL_PALETTE8_RGBA4_OES", GL_PALETTE8_RGBA4_OES},
    {"GL_PALETTE8_RGBA8_OES", GL_PALETTE8_RGBA8_OES},
    {"GL_PERSPECTIVE_CORRECTION_HINT", GL_PERSPECTIVE_CORRECTION_HINT},
    {"GL_POINTS", GL_POINTS},
    {"GL_POINT_DISTANCE_ATTENUATION", GL_POINT_DISTANCE_ATTENUATION},
    {"GL_POINT_FADE_THRESHOLD_SIZE", GL_POINT_FADE_THRESHOLD_SIZE},
    {"GL_POINT_SIZE", GL_POINT_SIZE},
    {"GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES", GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES},
    {"GL_POINT_SIZE_ARRAY_OES", GL_POINT_SIZE_ARRAY_OES},
    {"GL_POINT_SIZE_ARRAY_POINTER_OES", GL_POINT_SIZE_ARRAY_POINTER_OES},
    {"GL_POINT_SIZE_ARRAY_STRIDE_OES", GL_POINT_SIZE_ARRAY_STRIDE_OES},
    {"GL_POINT_SIZE_ARRAY_TYPE_OES", GL_POINT_SIZE_ARRAY_TYPE_OES},
    {"GL_POINT_SIZE_MAX", GL_POINT_SIZE_MAX},
    {"GL_POINT_SIZE_MIN", GL_POINT_SIZE_MIN},
    {"GL_POINT_SMOOTH", GL_POINT_SMOOTH},
    {"GL_POINT_SMOOTH_HINT", GL_POINT_SMOOTH_HINT},
    {"GL_POINT_SPRITE_OES", GL_POINT_SPRITE_OES},
    {"GL_POLYGON_OFFSET_FACTOR", GL_POLYGON_OFFSET_FACTOR},
    {"GL_POLYGON_OFFSET_FILL", GL_POLYGON_OFFSET_FILL},
    {"GL_POLYGON_OFFSET_UNITS", GL_POLYGON_OFFSET_UNITS},
    {"GL_POSITION", GL_POSITION},
    {"GL_PREVIOUS", GL_PREVIOUS},
    {"GL_PRIMARY_COLOR", GL_PRIMARY_COLOR},
    {"GL_PROGRAM_OBJECT_EXT", GL_PROGRAM_OBJECT_EXT},
    {"GL_PROGRAM_PIPELINE_BINDING_EXT", GL_PROGRAM_PIPELINE_BINDING_EXT},
    {"GL_PROGRAM_PIPELINE_OBJECT_EXT", GL_PROGRAM_PIPELINE_OBJECT_EXT},
    {"GL_PROGRAM_SEPARABLE_EXT", GL_PROGRAM_SEPARABLE_EXT},
    {"GL_PROJECTION", GL_PROJECTION},
    {"GL_PROJECTION_MATRIX", GL_PROJECTION_MATRIX},
    {"GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES", GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES},
    {"GL_PROJECTION_STACK_DEPTH", GL_PROJECTION_STACK_DEPTH},
    {"GL_QUADRATIC_ATTENUATION", GL_QUADRATIC_ATTENUATION},
    {"GL_QUERY_OBJECT_EXT", GL_QUERY_OBJECT_EXT},
    {"GL_QUERY_RESULT_AVAILABLE_EXT", GL_QUERY_RESULT_AVAILABLE_EXT},
    {"GL_QUERY_RESULT_EXT", GL_QUERY_RESULT_EXT},
    {"GL_R16F_EXT", GL_R16F_EXT},
    {"GL_R8_EXT", GL_R8_EXT},
    {"GL_READ_FRAMEBUFFER_APPLE", GL_READ_FRAMEBUFFER_APPLE},
    {"GL_READ_FRAMEBUFFER_BINDING_APPLE", GL_READ_FRAMEBUFFER_BINDING_APPLE},
    {"GL_RED_BITS", GL_RED_BITS},
    {"GL_RED_EXT", GL_RED_EXT},
    {"GL_RENDERBUFFER", GL_RENDERBUFFER},
    {"GL_RENDERBUFFER_ALPHA_SIZE", GL_RENDERBUFFER_ALPHA_SIZE},
    {"GL_RENDERBUFFER_ALPHA_SIZE_OES", GL_RENDERBUFFER_ALPHA_SIZE_OES},
    {"GL_RENDERBUFFER_BINDING", GL_RENDERBUFFER_BINDING},
    {"GL_RENDERBUFFER_BINDING_OES", GL_RENDERBUFFER_BINDING_OES},
    {"GL_RENDERBUFFER_BLUE_SIZE", GL_RENDERBUFFER_BLUE_SIZE},
    {"GL_RENDERBUFFER_BLUE_SIZE_OES", GL_RENDERBUFFER_BLUE_SIZE_OES},
    {"GL_RENDERBUFFER_DEPTH_SIZE", GL_RENDERBUFFER_DEPTH_SIZE},
    {"GL_RENDERBUFFER_DEPTH_SIZE_OES", GL_RENDERBUFFER_DEPTH_SIZE_OES},
    {"GL_RENDERBUFFER_GREEN_SIZE", GL_RENDERBUFFER_GREEN_SIZE},
    {"GL_RENDERBUFFER_GREEN_SIZE_OES", GL_RENDERBUFFER_GREEN_SIZE_OES},
    {"GL_RENDERBUFFER_HEIGHT", GL_RENDERBUFFER_HEIGHT},
    {"GL_RENDERBUFFER_HEIGHT_OES", GL_RENDERBUFFER_HEIGHT_OES},
    {"GL_RENDERBUFFER_INTERNAL_FORMAT", GL_RENDERBUFFER_INTERNAL_FORMAT},
    {"GL_RENDERBUFFER_INTERNAL_FORMAT_OES", GL_RENDERBUFFER_INTERNAL_FORMAT_OES},
    {"GL_RENDERBUFFER_OES", GL_RENDERBUFFER_OES},
    {"GL_RENDERBUFFER_RED_SIZE", GL_RENDERBUFFER_RED_SIZE},
    {"GL_RENDERBUFFER_RED_SIZE_OES", GL_RENDERBUFFER_RED_SIZE_OES},
    {"GL_RENDERBUFFER_SAMPLES_APPLE", GL_RENDERBUFFER_SAMPLES_APPLE},
    {"GL_RENDERBUFFER_STENCIL_SIZE", GL_RENDERBUFFER_STENCIL_SIZE},
    {"GL_RENDERBUFFER_STENCIL_SIZE_OES", GL_RENDERBUFFER_STENCIL_SIZE_OES},
    {"GL_RENDERBUFFER_WIDTH", GL_RENDERBUFFER_WIDTH},
    {"GL_RENDERBUFFER_WIDTH_OES", GL_RENDERBUFFER_WIDTH_OES},
    {"GL_RENDERER", GL_RENDERER},
    {"GL_REPEAT", GL_REPEAT},
    {"GL_REPLACE", GL_REPLACE},
    {"GL_RESCALE_NORMAL", GL_RESCALE_NORMAL},
    {"GL_RG16F_EXT", GL_RG16F_EXT},
    {"GL_RG8_EXT", GL_RG8_EXT},
    {"GL_RGB", GL_RGB},
    {"GL_RGB16F_EXT", GL_RGB16F_EXT},
    {"GL_RGB565", GL_RGB565},
    {"GL_RGB565_OES", GL_RGB565_OES},
    {"GL_RGB5_A1", GL_RGB5_A1},
    {"GL_RGB5_A1_OES", GL_RGB5_A1_OES},
    {"GL_RGB8_OES", GL_RGB8_OES},
    {"GL_RGBA", GL_RGBA},
    {"GL_RGBA16F_EXT", GL_RGBA16F_EXT},
    {"GL_RGBA4", GL_RGBA4},
    {"GL_RGBA4_OES", GL_RGBA4_OES},
    {"GL_RGBA8_OES", GL_RGBA8_OES},
    {"GL_RGB_422_APPLE", GL_RGB_422_APPLE},
    {"GL_RGB_SCALE", GL_RGB_SCALE},
    {"GL_RG_EXT", GL_RG_EXT},
    {"GL_SAMPLER_2D", GL_SAMPLER_2D},
    {"GL_SAMPLER_CUBE", GL_SAMPLER_CUBE},
    {"GL_SAMPLES", GL_SAMPLES},
    {"GL_SAMPLE_ALPHA_TO_COVERAGE", GL_SAMPLE_ALPHA_TO_COVERAGE},
    {"GL_SAMPLE_ALPHA_TO_ONE", GL_SAMPLE_ALPHA_TO_ONE},
    {"GL_SAMPLE_BUFFERS", GL_SAMPLE_BUFFERS},
    {"GL_SAMPLE_COVERAGE", GL_SAMPLE_COVERAGE},
    {"GL_SAMPLE_COVERAGE_INVERT", GL_SAMPLE_COVERAGE_INVERT},
    {"GL_SAMPLE_COVERAGE_VALUE", GL_SAMPLE_COVERAGE_VALUE},
    {"GL_SCISSOR_BOX", GL_SCISSOR_BOX},
    {"GL_SCISSOR_TEST", GL_SCISSOR_TEST},
    {"GL_SET", GL_SET},
    {"GL_SHADER_BINARY_FORMATS", GL_SHADER_BINARY_FORMATS},
    {"GL_SHADER_COMPILER", GL_SHADER_COMPILER},
    {"GL_SHADER_OBJECT_EXT", GL_SHADER_OBJECT_EXT},
    {"GL_SHADER_SOURCE_LENGTH", GL_SHADER_SOURCE_LENGTH},
    {"GL_SHADER_TYPE", GL_SHADER_TYPE},
    {"GL_SHADE_MODEL", GL_SHADE_MODEL},
    {"GL_SHADING_LANGUAGE_VERSION", GL_SHADING_LANGUAGE_VERSION},
    {"GL_SHININESS", GL_SHININESS},
    {"GL_SHORT", GL_SHORT},
    {"GL_SMOOTH", GL_SMOOTH},
    {"GL_SMOOTH_LINE_WIDTH_RANGE", GL_SMOOTH_LINE_WIDTH_RANGE},
    {"GL_SMOOTH_POINT_SIZE_RANGE", GL_SMOOTH_POINT_SIZE_RANGE},
    {"GL_SPECULAR", GL_SPECULAR},
    {"GL_SPOT_CUTOFF", GL_SPOT_CUTOFF},
    {"GL_SPOT_DIRECTION", GL_SPOT_DIRECTION},
    {"GL_SPOT_EXPONENT", GL_SPOT_EXPONENT},
    {"GL_SRC0_ALPHA", GL_SRC0_ALPHA},
    {"GL_SRC0_RGB", GL_SRC0_RGB},
    {"GL_SRC1_ALPHA", GL_SRC1_ALPHA},
    {"GL_SRC1_RGB", GL_SRC1_RGB},
    {"GL_SRC2_ALPHA", GL_SRC2_ALPHA},
    {"GL_SRC2_RGB", GL_SRC2_RGB},
    {"GL_SRC_ALPHA", GL_SRC_ALPHA},
    {"GL_SRC_ALPHA_SATURATE", GL_SRC_ALPHA_SATURATE},
    {"GL_SRC_COLOR", GL_SRC_COLOR},
    {"GL_STACK_OVERFLOW", GL_STACK_OVERFLOW},
    {"GL_STACK_UNDERFLOW", GL_STACK_UNDERFLOW},
    {"GL_STATIC_DRAW", GL_STATIC_DRAW},
    {"GL_STENCIL_ATTACHMENT", GL_STENCIL_ATTACHMENT},
    {"GL_STENCIL_ATTACHMENT_OES", GL_STENCIL_ATTACHMENT_OES},
    {"GL_STENCIL_BACK_FAIL", GL_STENCIL_BACK_FAIL},
    {"GL_STENCIL_BACK_FUNC", GL_STENCIL_BACK_FUNC},
    {"GL_STENCIL_BACK_PASS_DEPTH_FAIL", GL_STENCIL_BACK_PASS_DEPTH_FAIL},
    {"GL_STENCIL_BACK_PASS_DEPTH_PASS", GL_STENCIL_BACK_PASS_DEPTH_PASS},
    {"GL_STENCIL_BACK_REF", GL_STENCIL_BACK_REF},
    {"GL_STENCIL_BACK_VALUE_MASK", GL_STENCIL_BACK_VALUE_MASK},
    {"GL_STENCIL_BACK_WRITEMASK", GL_STENCIL_BACK_WRITEMASK},
    {"GL_STENCIL_BITS", GL_STENCIL_BITS},
    {"GL_STENCIL_BUFFER_BIT", GL_STENCIL_BUFFER_BIT},
    {"GL_STENCIL_CLEAR_VALUE", GL_STENCIL_CLEAR_VALUE},
    {"GL_STENCIL_EXT", GL_STENCIL_EXT},
    {"GL_STENCIL_FAIL", GL_STENCIL_FAIL},
    {"GL_STENCIL_FUNC", GL_STENCIL_FUNC},
    {"GL_STENCIL_INDEX", GL_STENCIL_INDEX},
    {"GL_STENCIL_INDEX8", GL_STENCIL_INDEX8},
    {"GL_STENCIL_INDEX8_OES", GL_STENCIL_INDEX8_OES},
    {"GL_STENCIL_PASS_DEPTH_FAIL", GL_STENCIL_PASS_DEPTH_FAIL},
    {"GL_STENCIL_PASS_DEPTH_PASS", GL_STENCIL_PASS_DEPTH_PASS},
    {"GL_STENCIL_REF", GL_STENCIL_REF},
    {"GL_STENCIL_TEST", GL_STENCIL_TEST},
    {"GL_STENCIL_VALUE_MASK", GL_STENCIL_VALUE_MASK},
    {"GL_STENCIL_WRITEMASK", GL_STENCIL_WRITEMASK},
    {"GL_STREAM_DRAW", GL_STREAM_DRAW},
    {"GL_SUBPIXEL_BITS", GL_SUBPIXEL_BITS},
    {"GL_SUBTRACT", GL_SUBTRACT},
    {"GL_TEXTURE", GL_TEXTURE},
    {"GL_TEXTURE0", GL_TEXTURE0},
    {"GL_TEXTURE1", GL_TEXTURE1},
    {"GL_TEXTURE10", GL_TEXTURE10},
    {"GL_TEXTURE11", GL_TEXTURE11},
    {"GL_TEXTURE12", GL_TEXTURE12},
    {"GL_TEXTURE13", GL_TEXTURE13},
    {"GL_TEXTURE14", GL_TEXTURE14},
    {"GL_TEXTURE15", GL_TEXTURE15},
    {"GL_TEXTURE16", GL_TEXTURE16},
    {"GL_TEXTURE17", GL_TEXTURE17},
    {"GL_TEXTURE18", GL_TEXTURE18},
    {"GL_TEXTURE19", GL_TEXTURE19},
    {"GL_TEXTURE2", GL_TEXTURE2},
    {"GL_TEXTURE20", GL_TEXTURE20},
    {"GL_TEXTURE21", GL_TEXTURE21},
    {"GL_TEXTURE22", GL_TEXTURE22},
    {"GL_TEXTURE23", GL_TEXTURE23},
    {"GL_TEXTURE24", GL_TEXTURE24},
    {"GL_TEXTURE25", GL_TEXTURE25},
    {"GL_TEXTURE26", GL_TEXTURE26},
    {"GL_TEXTURE27", GL_TEXTURE27},
    {"GL_TEXTURE28", GL_TEXTURE28},
    {"GL_TEXTURE29", GL_TEXTURE29},
    {"GL_TEXTURE3", GL_TEXTURE3},
    {"GL_TEXTURE30", GL_TEXTURE30},
    {"GL_TEXTURE31", GL_TEXTURE31},
    {"GL_TEXTURE4", GL_TEXTURE4},
    {"GL_TEXTURE5", GL_TEXTURE5},
    {"GL_TEXTURE6", GL_TEXTURE6},
    {"GL_TEXTURE7", GL_TEXTURE7},
    {"GL_TEXTURE8", GL_TEXTURE8},
    {"GL_TEXTURE9", GL_TEXTURE9},
    {"GL_TEXTURE_2D", GL_TEXTURE_2D},
    {"GL_TEXTURE_BINDING_2D", GL_TEXTURE_BINDING_2D},
    {"GL_TEXTURE_BINDING_CUBE_MAP", GL_TEXTURE_BINDING_CUBE_MAP},
    {"GL_TEXTURE_COMPARE_FUNC_EXT", GL_TEXTURE_COMPARE_FUNC_EXT},
    {"GL_TEXTURE_COMPARE_MODE_EXT", GL_TEXTURE_COMPARE_MODE_EXT},
    {"GL_TEXTURE_COORD_ARRAY", GL_TEXTURE_COORD_ARRAY},
    {"GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING", GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING},
    {"GL_TEXTURE_COORD_ARRAY_POINTER", GL_TEXTURE_COORD_ARRAY_POINTER},
    {"GL_TEXTURE_COORD_ARRAY_SIZE", GL_TEXTURE_COORD_ARRAY_SIZE},
    {"GL_TEXTURE_COORD_ARRAY_STRIDE", GL_TEXTURE_COORD_ARRAY_STRIDE},
    {"GL_TEXTURE_COORD_ARRAY_TYPE", GL_TEXTURE_COORD_ARRAY_TYPE},
    {"GL_TEXTURE_CROP_RECT_OES", GL_TEXTURE_CROP_RECT_OES},
    {"GL_TEXTURE_CUBE_MAP", GL_TEXTURE_CUBE_MAP},
    {"GL_TEXTURE_CUBE_MAP_NEGATIVE_X", GL_TEXTURE_CUBE_MAP_NEGATIVE_X},
    {"GL_TEXTURE_CUBE_MAP_NEGATIVE_Y", GL_TEXTURE_CUBE_MAP_NEGATIVE_Y},
    {"GL_TEXTURE_CUBE_MAP_NEGATIVE_Z", GL_TEXTURE_CUBE_MAP_NEGATIVE_Z},
    {"GL_TEXTURE_CUBE_MAP_POSITIVE_X", GL_TEXTURE_CUBE_MAP_POSITIVE_X},
    {"GL_TEXTURE_CUBE_MAP_POSITIVE_Y", GL_TEXTURE_CUBE_MAP_POSITIVE_Y},
    {"GL_TEXTURE_CUBE_MAP_POSITIVE_Z", GL_TEXTURE_CUBE_MAP_POSITIVE_Z},
    {"GL_TEXTURE_ENV", GL_TEXTURE_ENV},
    {"GL_TEXTURE_ENV_COLOR", GL_TEXTURE_ENV_COLOR},
    {"GL_TEXTURE_ENV_MODE", GL_TEXTURE_ENV_MODE},
    {"GL_TEXTURE_FILTER_CONTROL_EXT", GL_TEXTURE_FILTER_CONTROL_EXT},
    {"GL_TEXTURE_LOD_BIAS_EXT", GL_TEXTURE_LOD_BIAS_EXT},
    {"GL_TEXTURE_MAG_FILTER", GL_TEXTURE_MAG_FILTER},
    {"GL_TEXTURE_MATRIX", GL_TEXTURE_MATRIX},
    {"GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES", GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES},
    {"GL_TEXTURE_MAX_ANISOTROPY_EXT", GL_TEXTURE_MAX_ANISOTROPY_EXT},
    {"GL_TEXTURE_MAX_LEVEL_APPLE", GL_TEXTURE_MAX_LEVEL_APPLE},
    {"GL_TEXTURE_MIN_FILTER", GL_TEXTURE_MIN_FILTER},
    {"GL_TEXTURE_STACK_DEPTH", GL_TEXTURE_STACK_DEPTH},
    {"GL_TEXTURE_WRAP_S", GL_TEXTURE_WRAP_S},
    {"GL_TEXTURE_WRAP_T", GL_TEXTURE_WRAP_T},
    {"GL_TRIANGLES", GL_TRIANGLES},
    {"GL_TRIANGLE_FAN", GL_TRIANGLE_FAN},
    {"GL_TRIANGLE_STRIP", GL_TRIANGLE_STRIP},
    {"GL_TRUE", GL_TRUE},
    {"GL_UNPACK_ALIGNMENT", GL_UNPACK_ALIGNMENT},
    {"GL_UNSIGNED_BYTE", GL_UNSIGNED_BYTE},
    {"GL_UNSIGNED_INT", GL_UNSIGNED_INT},
    {"GL_UNSIGNED_INT_24_8_OES", GL_UNSIGNED_INT_24_8_OES},
    {"GL_UNSIGNED_INT_OES", GL_UNSIGNED_INT_OES},
    {"GL_UNSIGNED_NORMALIZED_EXT", GL_UNSIGNED_NORMALIZED_EXT},
    {"GL_UNSIGNED_SHORT", GL_UNSIGNED_SHORT},
    {"GL_UNSIGNED_SHORT_1_5_5_5_REV", GL_UNSIGNED_SHORT_1_5_5_5_REV},
    {"GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT", GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT},
    {"GL_UNSIGNED_SHORT_4_4_4_4", GL_UNSIGNED_SHORT_4_4_4_4},
    {"GL_UNSIGNED_SHORT_4_4_4_4_REV", GL_UNSIGNED_SHORT_4_4_4_4_REV},
    {"GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT", GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT},
    {"GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG", GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG},
    {"GL_UNSIGNED_SHORT_5_5_5_1", GL_UNSIGNED_SHORT_5_5_5_1},
    {"GL_UNSIGNED_SHORT_5_6_5", GL_UNSIGNED_SHORT_5_6_5},
    {"GL_UNSIGNED_SHORT_8_8_APPLE", GL_UNSIGNED_SHORT_8_8_APPLE},
    {"GL_UNSIGNED_SHORT_8_8_REV_APPLE", GL_UNSIGNED_SHORT_8_8_REV_APPLE},
    {"GL_VALIDATE_STATUS", GL_VALIDATE_STATUS},
    {"GL_VENDOR", GL_VENDOR},
    {"GL_VERSION", GL_VERSION},
    {"GL_VERSION_ES_CL_1_0", GL_VERSION_ES_CL_1_0},
    {"GL_VERSION_ES_CL_1_1", GL_VERSION_ES_CL_1_1},
    {"GL_VERSION_ES_CM_1_0", GL_VERSION_ES_CM_1_0},
    {"GL_VERSION_ES_CM_1_1", GL_VERSION_ES_CM_1_1},
    {"GL_VERTEX_ARRAY", GL_VERTEX_ARRAY},
    {"GL_VERTEX_ARRAY_BINDING_OES", GL_VERTEX_ARRAY_BINDING_OES},
    {"GL_VERTEX_ARRAY_BUFFER_BINDING", GL_VERTEX_ARRAY_BUFFER_BINDING},
    {"GL_VERTEX_ARRAY_OBJECT_EXT", GL_VERTEX_ARRAY_OBJECT_EXT},
    {"GL_VERTEX_ARRAY_POINTER", GL_VERTEX_ARRAY_POINTER},
    {"GL_VERTEX_ARRAY_SIZE", GL_VERTEX_ARRAY_SIZE},
    {"GL_VERTEX_ARRAY_STRIDE", GL_VERTEX_ARRAY_STRIDE},
    {"GL_VERTEX_ARRAY_TYPE", GL_VERTEX_ARRAY_TYPE},
    {"GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING", GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING},
    {"GL_VERTEX_ATTRIB_ARRAY_ENABLED", GL_VERTEX_ATTRIB_ARRAY_ENABLED},
    {"GL_VERTEX_ATTRIB_ARRAY_NORMALIZED", GL_VERTEX_ATTRIB_ARRAY_NORMALIZED},
    {"GL_VERTEX_ATTRIB_ARRAY_POINTER", GL_VERTEX_ATTRIB_ARRAY_POINTER},
    {"GL_VERTEX_ATTRIB_ARRAY_SIZE", GL_VERTEX_ATTRIB_ARRAY_SIZE},
    {"GL_VERTEX_ATTRIB_ARRAY_STRIDE", GL_VERTEX_ATTRIB_ARRAY_STRIDE},
    {"GL_VERTEX_ATTRIB_ARRAY_TYPE", GL_VERTEX_ATTRIB_ARRAY_TYPE},
    {"GL_VERTEX_SHADER", GL_VERTEX_SHADER},
    {"GL_VERTEX_SHADER_BIT_EXT", GL_VERTEX_SHADER_BIT_EXT},
    {"GL_VIEWPORT", GL_VIEWPORT},
    {"GL_WEIGHT_ARRAY_BUFFER_BINDING_OES", GL_WEIGHT_ARRAY_BUFFER_BINDING_OES},
    {"GL_WEIGHT_ARRAY_OES", GL_WEIGHT_ARRAY_OES},
    {"GL_WEIGHT_ARRAY_POINTER_OES", GL_WEIGHT_ARRAY_POINTER_OES},
    {"GL_WEIGHT_ARRAY_SIZE_OES", GL_WEIGHT_ARRAY_SIZE_OES},
    {"GL_WEIGHT_ARRAY_STRIDE_OES", GL_WEIGHT_ARRAY_STRIDE_OES},
    {"GL_WEIGHT_ARRAY_TYPE_OES", GL_WEIGHT_ARRAY_TYPE_OES},
    {"GL_WRITE_ONLY_OES", GL_WRITE_ONLY_OES},
    {"GL_XOR", GL_XOR},
    {"GL_ZERO", GL_ZERO},
    {"kEAGLRenderingAPIOpenGLES1", kEAGLRenderingAPIOpenGLES1},
    {"kEAGLRenderingAPIOpenGLES2", kEAGLRenderingAPIOpenGLES2},
    {NULL, 0}
};

static int _luaObjC_glActiveTexture(lua_State *L)
{
    glActiveTexture(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glAlphaFunc(lua_State *L)
{
    glAlphaFunc(lua_tointeger(L, 1),
                lua_tonumber(L, 2))
    ;
    return 0;
}
static int _luaObjC_glAlphaFuncx(lua_State *L)
{
    glAlphaFuncx(lua_tointeger(L, 1),
                 lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glBindBuffer(lua_State *L)
{
    glBindBuffer(lua_tointeger(L, 1),
                 lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glBindFramebufferOES(lua_State *L)
{
    glBindFramebufferOES(lua_tointeger(L, 1),
                         lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glBindRenderbufferOES(lua_State *L)
{
    glBindRenderbufferOES(lua_tointeger(L, 1),
                          lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glBindTexture(lua_State *L)
{
    glBindTexture(lua_tointeger(L, 1),
                  lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glBlendEquationOES(lua_State *L)
{
    glBlendEquationOES(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glBlendFunc(lua_State *L)
{
    glBlendFunc(lua_tointeger(L, 1),
                lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glBufferData(lua_State *L)
{
    glBufferData(lua_tointeger(L, 1),
                 lua_tointeger(L, 2),
                 lua_touserdata(L, 3),
                 lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glBufferSubData(lua_State *L)
{
    glBufferSubData(lua_tointeger(L, 1),
                    lua_tointeger(L, 2),
                    lua_tointeger(L, 3),
                    lua_touserdata(L, 4))
    ;
    return 0;
}
static int _luaObjC_glCheckFramebufferStatusOES(lua_State *L)
{
    lua_pushinteger(L, glCheckFramebufferStatusOES(lua_tointeger(L, 1))
                    );
    return 1;
}
static int _luaObjC_glClear(lua_State *L)
{
    glClear(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glClearColor(lua_State *L)
{
    glClearColor(lua_tonumber(L, 1),
                 lua_tonumber(L, 2),
                 lua_tonumber(L, 3),
                 lua_tonumber(L, 4))
    ;
    return 0;
}
static int _luaObjC_glClearColorx(lua_State *L)
{
    glClearColorx(lua_tointeger(L, 1),
                  lua_tointeger(L, 2),
                  lua_tointeger(L, 3),
                  lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glClearDepthf(lua_State *L)
{
    glClearDepthf(lua_tonumber(L, 1))
    ;
    return 0;
}
static int _luaObjC_glClearDepthx(lua_State *L)
{
    glClearDepthx(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glClearStencil(lua_State *L)
{
    glClearStencil(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glClientActiveTexture(lua_State *L)
{
    glClientActiveTexture(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glClipPlanef(lua_State *L)
{
    glClipPlanef(lua_tointeger(L, 1),
                 lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glClipPlanex(lua_State *L)
{
    glClipPlanex(lua_tointeger(L, 1),
                 lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glColor4f(lua_State *L)
{
    glColor4f(lua_tonumber(L, 1),
              lua_tonumber(L, 2),
              lua_tonumber(L, 3),
              lua_tonumber(L, 4))
    ;
    return 0;
}
static int _luaObjC_glColor4ub(lua_State *L)
{
    glColor4ub(lua_tointeger(L, 1),
               lua_tointeger(L, 2),
               lua_tointeger(L, 3),
               lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glColor4x(lua_State *L)
{
    glColor4x(lua_tointeger(L, 1),
              lua_tointeger(L, 2),
              lua_tointeger(L, 3),
              lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glColorMask(lua_State *L)
{
    glColorMask(lua_tointeger(L, 1),
                lua_tointeger(L, 2),
                lua_tointeger(L, 3),
                lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glColorPointer(lua_State *L)
{
    glColorPointer(lua_tointeger(L, 1),
                   lua_tointeger(L, 2),
                   lua_tointeger(L, 3),
                   lua_touserdata(L, 4))
    ;
    return 0;
}
static int _luaObjC_glCompressedTexImage2D(lua_State *L)
{
    glCompressedTexImage2D(lua_tointeger(L, 1),
                           lua_tointeger(L, 2),
                           lua_tointeger(L, 3),
                           lua_tointeger(L, 4),
                           lua_tointeger(L, 5),
                           lua_tointeger(L, 6),
                           lua_tointeger(L, 7),
                           lua_touserdata(L, 8))
    ;
    return 0;
}
static int _luaObjC_glCompressedTexSubImage2D(lua_State *L)
{
    glCompressedTexSubImage2D(lua_tointeger(L, 1),
                              lua_tointeger(L, 2),
                              lua_tointeger(L, 3),
                              lua_tointeger(L, 4),
                              lua_tointeger(L, 5),
                              lua_tointeger(L, 6),
                              lua_tointeger(L, 7),
                              lua_tointeger(L, 8),
                              lua_touserdata(L, 9))
    ;
    return 0;
}
static int _luaObjC_glCopyTexImage2D(lua_State *L)
{
    glCopyTexImage2D(lua_tointeger(L, 1),
                     lua_tointeger(L, 2),
                     lua_tointeger(L, 3),
                     lua_tointeger(L, 4),
                     lua_tointeger(L, 5),
                     lua_tointeger(L, 6),
                     lua_tointeger(L, 7),
                     lua_tointeger(L, 8))
    ;
    return 0;
}
static int _luaObjC_glCopyTexSubImage2D(lua_State *L)
{
    glCopyTexSubImage2D(lua_tointeger(L, 1),
                        lua_tointeger(L, 2),
                        lua_tointeger(L, 3),
                        lua_tointeger(L, 4),
                        lua_tointeger(L, 5),
                        lua_tointeger(L, 6),
                        lua_tointeger(L, 7),
                        lua_tointeger(L, 8))
    ;
    return 0;
}
static int _luaObjC_glCullFace(lua_State *L)
{
    glCullFace(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glCurrentPaletteMatrixOES(lua_State *L)
{
    glCurrentPaletteMatrixOES(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glDeleteBuffers(lua_State *L)
{
    glDeleteBuffers(lua_tointeger(L, 1),
                    lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glDeleteFramebuffersOES(lua_State *L)
{
    glDeleteFramebuffersOES(lua_tointeger(L, 1),
                            lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glDeleteRenderbuffersOES(lua_State *L)
{
    glDeleteRenderbuffersOES(lua_tointeger(L, 1),
                             lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glDeleteTextures(lua_State *L)
{
    glDeleteTextures(lua_tointeger(L, 1),
                     lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glDepthFunc(lua_State *L)
{
    glDepthFunc(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glDepthMask(lua_State *L)
{
    glDepthMask(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glDepthRangef(lua_State *L)
{
    glDepthRangef(lua_tonumber(L, 1),
                  lua_tonumber(L, 2))
    ;
    return 0;
}
static int _luaObjC_glDepthRangex(lua_State *L)
{
    glDepthRangex(lua_tointeger(L, 1),
                  lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glDisable(lua_State *L)
{
    glDisable(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glDisableClientState(lua_State *L)
{
    glDisableClientState(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glDrawArrays(lua_State *L)
{
    glDrawArrays(lua_tointeger(L, 1),
                 lua_tointeger(L, 2),
                 lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glDrawElements(lua_State *L)
{
    glDrawElements(lua_tointeger(L, 1),
                   lua_tointeger(L, 2),
                   lua_tointeger(L, 3),
                   lua_touserdata(L, 4))
    ;
    return 0;
}
static int _luaObjC_glDrawTexfOES(lua_State *L)
{
    glDrawTexfOES(lua_tonumber(L, 1),
                  lua_tonumber(L, 2),
                  lua_tonumber(L, 3),
                  lua_tonumber(L, 4),
                  lua_tonumber(L, 5))
    ;
    return 0;
}
static int _luaObjC_glDrawTexfvOES(lua_State *L)
{
    glDrawTexfvOES(lua_touserdata(L, 1))
    ;
    return 0;
}
static int _luaObjC_glDrawTexiOES(lua_State *L)
{
    glDrawTexiOES(lua_tointeger(L, 1),
                  lua_tointeger(L, 2),
                  lua_tointeger(L, 3),
                  lua_tointeger(L, 4),
                  lua_tointeger(L, 5))
    ;
    return 0;
}
static int _luaObjC_glDrawTexivOES(lua_State *L)
{
    glDrawTexivOES(lua_touserdata(L, 1))
    ;
    return 0;
}
static int _luaObjC_glDrawTexsOES(lua_State *L)
{
    glDrawTexsOES(lua_tointeger(L, 1),
                  lua_tointeger(L, 2),
                  lua_tointeger(L, 3),
                  lua_tointeger(L, 4),
                  lua_tointeger(L, 5))
    ;
    return 0;
}
static int _luaObjC_glDrawTexsvOES(lua_State *L)
{
    glDrawTexsvOES(lua_touserdata(L, 1))
    ;
    return 0;
}
static int _luaObjC_glDrawTexxOES(lua_State *L)
{
    glDrawTexxOES(lua_tointeger(L, 1),
                  lua_tointeger(L, 2),
                  lua_tointeger(L, 3),
                  lua_tointeger(L, 4),
                  lua_tointeger(L, 5))
    ;
    return 0;
}
static int _luaObjC_glDrawTexxvOES(lua_State *L)
{
    glDrawTexxvOES(lua_touserdata(L, 1))
    ;
    return 0;
}
static int _luaObjC_glEnable(lua_State *L)
{
    glEnable(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glEnableClientState(lua_State *L)
{
    glEnableClientState(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glFinish(lua_State *L)
{
    glFinish();
    return 0;
}
static int _luaObjC_glFlush(lua_State *L)
{
    glFlush();
    return 0;
}
static int _luaObjC_glFogf(lua_State *L)
{
    glFogf(lua_tointeger(L, 1),
           lua_tonumber(L, 2))
    ;
    return 0;
}
static int _luaObjC_glFogfv(lua_State *L)
{
    glFogfv(lua_tointeger(L, 1),
            lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glFogx(lua_State *L)
{
    glFogx(lua_tointeger(L, 1),
           lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glFogxv(lua_State *L)
{
    glFogxv(lua_tointeger(L, 1),
            lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glFramebufferRenderbufferOES(lua_State *L)
{
    glFramebufferRenderbufferOES(lua_tointeger(L, 1),
                                 lua_tointeger(L, 2),
                                 lua_tointeger(L, 3),
                                 lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glFramebufferTexture2DOES(lua_State *L)
{
    glFramebufferTexture2DOES(lua_tointeger(L, 1),
                              lua_tointeger(L, 2),
                              lua_tointeger(L, 3),
                              lua_tointeger(L, 4),
                              lua_tointeger(L, 5))
    ;
    return 0;
}
static int _luaObjC_glFrontFace(lua_State *L)
{
    glFrontFace(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glFrustumf(lua_State *L)
{
    glFrustumf(lua_tonumber(L, 1),
               lua_tonumber(L, 2),
               lua_tonumber(L, 3),
               lua_tonumber(L, 4),
               lua_tonumber(L, 5),
               lua_tonumber(L, 6))
    ;
    return 0;
}
static int _luaObjC_glFrustumx(lua_State *L)
{
    glFrustumx(lua_tointeger(L, 1),
               lua_tointeger(L, 2),
               lua_tointeger(L, 3),
               lua_tointeger(L, 4),
               lua_tointeger(L, 5),
               lua_tointeger(L, 6))
    ;
    return 0;
}
static int _luaObjC_glGenBuffers(lua_State *L)
{
    glGenBuffers(lua_tointeger(L, 1),
                 lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGenFramebuffersOES(lua_State *L)
{
    glGenFramebuffersOES(lua_tointeger(L, 1),
                         lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGenRenderbuffersOES(lua_State *L)
{
    glGenRenderbuffersOES(lua_tointeger(L, 1),
                          lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGenTextures(lua_State *L)
{
    glGenTextures(lua_tointeger(L, 1),
                  lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGenerateMipmapOES(lua_State *L)
{
    glGenerateMipmapOES(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glGetBooleanv(lua_State *L)
{
    GLboolean ret;
    glGetBooleanv(lua_tointeger(L, 1), &ret);
    lua_pushboolean(L, ret);
    return 1;
}
static int _luaObjC_glGetBufferParameteriv(lua_State *L)
{
    glGetBufferParameteriv(lua_tointeger(L, 1),
                           lua_tointeger(L, 2),
                           lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetBufferPointervOES(lua_State *L)
{
    glGetBufferPointervOES(lua_tointeger(L, 1),
                           lua_tointeger(L, 2),
                           lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetClipPlanef(lua_State *L)
{
    glGetClipPlanef(lua_tointeger(L, 1),
                    lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGetClipPlanex(lua_State *L)
{
    glGetClipPlanex(lua_tointeger(L, 1),
                    lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGetError(lua_State *L)
{
    lua_pushinteger(L, glGetError());
    return 1;
}
static int _luaObjC_glGetFixedv(lua_State *L)
{
    glGetFixedv(lua_tointeger(L, 1),
                lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGetFloatv(lua_State *L)
{
    glGetFloatv(lua_tointeger(L, 1),
                lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGetFramebufferAttachmentParameterivOES(lua_State *L)
{
    glGetFramebufferAttachmentParameterivOES(lua_tointeger(L, 1),
                                             lua_tointeger(L, 2),
                                             lua_tointeger(L, 3),
                                             lua_touserdata(L, 4))
    ;
    return 0;
}
static int _luaObjC_glGetIntegerv(lua_State *L)
{
    glGetIntegerv(lua_tointeger(L, 1),
                  lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGetLightfv(lua_State *L)
{
    glGetLightfv(lua_tointeger(L, 1),
                 lua_tointeger(L, 2),
                 lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetLightxv(lua_State *L)
{
    glGetLightxv(lua_tointeger(L, 1),
                 lua_tointeger(L, 2),
                 lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetMaterialfv(lua_State *L)
{
    glGetMaterialfv(lua_tointeger(L, 1),
                    lua_tointeger(L, 2),
                    lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetMaterialxv(lua_State *L)
{
    glGetMaterialxv(lua_tointeger(L, 1),
                    lua_tointeger(L, 2),
                    lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetPointerv(lua_State *L)
{
    glGetPointerv(lua_tointeger(L, 1),
                  lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glGetRenderbufferParameterivOES(lua_State *L)
{
    glGetRenderbufferParameterivOES(lua_tointeger(L, 1),
                                    lua_tointeger(L, 2),
                                    lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetString(lua_State *L)
{
    lua_pushstring(L, (const char*)glGetString(lua_tointeger(L, 1))
                   );
    return 1;
}
static int _luaObjC_glGetTexEnvfv(lua_State *L)
{
    glGetTexEnvfv(lua_tointeger(L, 1),
                  lua_tointeger(L, 2),
                  lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetTexEnviv(lua_State *L)
{
    glGetTexEnviv(lua_tointeger(L, 1),
                  lua_tointeger(L, 2),
                  lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetTexEnvxv(lua_State *L)
{
    glGetTexEnvxv(lua_tointeger(L, 1),
                  lua_tointeger(L, 2),
                  lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetTexParameterfv(lua_State *L)
{
    glGetTexParameterfv(lua_tointeger(L, 1),
                        lua_tointeger(L, 2),
                        lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetTexParameteriv(lua_State *L)
{
    glGetTexParameteriv(lua_tointeger(L, 1),
                        lua_tointeger(L, 2),
                        lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glGetTexParameterxv(lua_State *L)
{
    glGetTexParameterxv(lua_tointeger(L, 1),
                        lua_tointeger(L, 2),
                        lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glHint(lua_State *L)
{
    glHint(lua_tointeger(L, 1),
           lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glIsBuffer(lua_State *L)
{
    lua_pushinteger(L, glIsBuffer(lua_tointeger(L, 1))
                    );
    return 1;
}
static int _luaObjC_glIsEnabled(lua_State *L)
{
    lua_pushinteger(L, glIsEnabled(lua_tointeger(L, 1))
                    );
    return 1;
}
static int _luaObjC_glIsFramebufferOES(lua_State *L)
{
    lua_pushinteger(L, glIsFramebufferOES(lua_tointeger(L, 1))
                    );
    return 1;
}
static int _luaObjC_glIsProgram(lua_State *L)
{
    lua_pushinteger(L, glIsProgram(lua_tointeger(L, 1))
                    );
    return 1;
}
static int _luaObjC_glIsRenderbufferOES(lua_State *L)
{
    lua_pushinteger(L, glIsRenderbufferOES(lua_tointeger(L, 1))
                    );
    return 1;
}
static int _luaObjC_glIsTexture(lua_State *L)
{
    lua_pushinteger(L, glIsTexture(lua_tointeger(L, 1))
                    );
    return 1;
}
static int _luaObjC_glLightModelf(lua_State *L)
{
    glLightModelf(lua_tointeger(L, 1),
                  lua_tonumber(L, 2))
    ;
    return 0;
}
static int _luaObjC_glLightModelfv(lua_State *L)
{
    glLightModelfv(lua_tointeger(L, 1),
                   lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glLightModelx(lua_State *L)
{
    glLightModelx(lua_tointeger(L, 1),
                  lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glLightModelxv(lua_State *L)
{
    glLightModelxv(lua_tointeger(L, 1),
                   lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glLightf(lua_State *L)
{
    glLightf(lua_tointeger(L, 1),
             lua_tointeger(L, 2),
             lua_tonumber(L, 3))
    ;
    return 0;
}
static int _luaObjC_glLightfv(lua_State *L)
{
    glLightfv(lua_tointeger(L, 1),
              lua_tointeger(L, 2),
              lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glLightx(lua_State *L)
{
    glLightx(lua_tointeger(L, 1),
             lua_tointeger(L, 2),
             lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glLightxv(lua_State *L)
{
    glLightxv(lua_tointeger(L, 1),
              lua_tointeger(L, 2),
              lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glLineWidth(lua_State *L)
{
    glLineWidth(lua_tonumber(L, 1))
    ;
    return 0;
}
static int _luaObjC_glLineWidthx(lua_State *L)
{
    glLineWidthx(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glLoadIdentity(lua_State *L)
{
    glLoadIdentity();
    return 0;
}
static int _luaObjC_glLoadMatrixf(lua_State *L)
{
    glLoadMatrixf(lua_touserdata(L, 1))
    ;
    return 0;
}
static int _luaObjC_glLoadMatrixx(lua_State *L)
{
    glLoadMatrixx(lua_touserdata(L, 1))
    ;
    return 0;
}
static int _luaObjC_glLoadPaletteFromModelViewMatrixOES(lua_State *L)
{
    glLoadPaletteFromModelViewMatrixOES();
    return 0;
}
static int _luaObjC_glLogicOp(lua_State *L)
{
    glLogicOp(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glMapBufferOES(lua_State *L)
{
    lua_pushlightuserdata(L, glMapBufferOES(lua_tointeger(L, 1),
                                            lua_tointeger(L, 2))
                          );
    return 1;
}
static int _luaObjC_glMaterialf(lua_State *L)
{
    glMaterialf(lua_tointeger(L, 1),
                lua_tointeger(L, 2),
                lua_tonumber(L, 3))
    ;
    return 0;
}
static int _luaObjC_glMaterialfv(lua_State *L)
{
    glMaterialfv(lua_tointeger(L, 1),
                 lua_tointeger(L, 2),
                 lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glMaterialx(lua_State *L)
{
    glMaterialx(lua_tointeger(L, 1),
                lua_tointeger(L, 2),
                lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glMaterialxv(lua_State *L)
{
    glMaterialxv(lua_tointeger(L, 1),
                 lua_tointeger(L, 2),
                 lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glMatrixIndexPointerOES(lua_State *L)
{
    glMatrixIndexPointerOES(lua_tointeger(L, 1),
                            lua_tointeger(L, 2),
                            lua_tointeger(L, 3),
                            lua_touserdata(L, 4))
    ;
    return 0;
}
static int _luaObjC_glMatrixMode(lua_State *L)
{
    glMatrixMode(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glMultMatrixf(lua_State *L)
{
    glMultMatrixf(lua_touserdata(L, 1))
    ;
    return 0;
}
static int _luaObjC_glMultMatrixx(lua_State *L)
{
    glMultMatrixx(lua_touserdata(L, 1))
    ;
    return 0;
}
static int _luaObjC_glMultiTexCoord4f(lua_State *L)
{
    glMultiTexCoord4f(lua_tointeger(L, 1),
                      lua_tonumber(L, 2),
                      lua_tonumber(L, 3),
                      lua_tonumber(L, 4),
                      lua_tonumber(L, 5))
    ;
    return 0;
}
static int _luaObjC_glMultiTexCoord4x(lua_State *L)
{
    glMultiTexCoord4x(lua_tointeger(L, 1),
                      lua_tointeger(L, 2),
                      lua_tointeger(L, 3),
                      lua_tointeger(L, 4),
                      lua_tointeger(L, 5))
    ;
    return 0;
}
static int _luaObjC_glNormal3f(lua_State *L)
{
    glNormal3f(lua_tonumber(L, 1),
               lua_tonumber(L, 2),
               lua_tonumber(L, 3))
    ;
    return 0;
}
static int _luaObjC_glNormal3x(lua_State *L)
{
    glNormal3x(lua_tointeger(L, 1),
               lua_tointeger(L, 2),
               lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glNormalPointer(lua_State *L)
{
    glNormalPointer(lua_tointeger(L, 1),
                    lua_tointeger(L, 2),
                    lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glOrthof(lua_State *L)
{
    glOrthof(lua_tonumber(L, 1),
             lua_tonumber(L, 2),
             lua_tonumber(L, 3),
             lua_tonumber(L, 4),
             lua_tonumber(L, 5),
             lua_tonumber(L, 6))
    ;
    return 0;
}
static int _luaObjC_glOrthox(lua_State *L)
{
    glOrthox(lua_tointeger(L, 1),
             lua_tointeger(L, 2),
             lua_tointeger(L, 3),
             lua_tointeger(L, 4),
             lua_tointeger(L, 5),
             lua_tointeger(L, 6))
    ;
    return 0;
}
static int _luaObjC_glPixelStorei(lua_State *L)
{
    glPixelStorei(lua_tointeger(L, 1),
                  lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glPointParameterf(lua_State *L)
{
    glPointParameterf(lua_tointeger(L, 1),
                      lua_tonumber(L, 2))
    ;
    return 0;
}
static int _luaObjC_glPointParameterfv(lua_State *L)
{
    glPointParameterfv(lua_tointeger(L, 1),
                       lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glPointParameterx(lua_State *L)
{
    glPointParameterx(lua_tointeger(L, 1),
                      lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glPointParameterxv(lua_State *L)
{
    glPointParameterxv(lua_tointeger(L, 1),
                       lua_touserdata(L, 2))
    ;
    return 0;
}
static int _luaObjC_glPointSize(lua_State *L)
{
    glPointSize(lua_tonumber(L, 1))
    ;
    return 0;
}
static int _luaObjC_glPointSizePointerOES(lua_State *L)
{
    glPointSizePointerOES(lua_tointeger(L, 1),
                          lua_tointeger(L, 2),
                          lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glPointSizex(lua_State *L)
{
    glPointSizex(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glPolygonOffset(lua_State *L)
{
    glPolygonOffset(lua_tonumber(L, 1),
                    lua_tonumber(L, 2))
    ;
    return 0;
}
static int _luaObjC_glPolygonOffsetx(lua_State *L)
{
    glPolygonOffsetx(lua_tointeger(L, 1),
                     lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glPopMatrix(lua_State *L)
{
    glPopMatrix();
    return 0;
}
static int _luaObjC_glPushMatrix(lua_State *L)
{
    glPushMatrix();
    return 0;
}
static int _luaObjC_glReadPixels(lua_State *L)
{
    glReadPixels(lua_tointeger(L, 1),
                 lua_tointeger(L, 2),
                 lua_tointeger(L, 3),
                 lua_tointeger(L, 4),
                 lua_tointeger(L, 5),
                 lua_tointeger(L, 6),
                 lua_touserdata(L, 7))
    ;
    return 0;
}
static int _luaObjC_glRenderbufferStorageOES(lua_State *L)
{
    glRenderbufferStorageOES(lua_tointeger(L, 1),
                             lua_tointeger(L, 2),
                             lua_tointeger(L, 3),
                             lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glRotatef(lua_State *L)
{
    glRotatef(lua_tonumber(L, 1),
              lua_tonumber(L, 2),
              lua_tonumber(L, 3),
              lua_tonumber(L, 4))
    ;
    return 0;
}
static int _luaObjC_glRotatex(lua_State *L)
{
    glRotatex(lua_tointeger(L, 1),
              lua_tointeger(L, 2),
              lua_tointeger(L, 3),
              lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glSampleCoverage(lua_State *L)
{
    glSampleCoverage(lua_tonumber(L, 1),
                     lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glSampleCoveragex(lua_State *L)
{
    glSampleCoveragex(lua_tointeger(L, 1),
                      lua_tointeger(L, 2))
    ;
    return 0;
}
static int _luaObjC_glScalef(lua_State *L)
{
    glScalef(lua_tonumber(L, 1),
             lua_tonumber(L, 2),
             lua_tonumber(L, 3))
    ;
    return 0;
}
static int _luaObjC_glScalex(lua_State *L)
{
    glScalex(lua_tointeger(L, 1),
             lua_tointeger(L, 2),
             lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glScissor(lua_State *L)
{
    glScissor(lua_tointeger(L, 1),
              lua_tointeger(L, 2),
              lua_tointeger(L, 3),
              lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glShadeModel(lua_State *L)
{
    glShadeModel(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glStencilFunc(lua_State *L)
{
    glStencilFunc(lua_tointeger(L, 1),
                  lua_tointeger(L, 2),
                  lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glStencilMask(lua_State *L)
{
    glStencilMask(lua_tointeger(L, 1))
    ;
    return 0;
}
static int _luaObjC_glStencilOp(lua_State *L)
{
    glStencilOp(lua_tointeger(L, 1),
                lua_tointeger(L, 2),
                lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexCoordPointer(lua_State *L)
{
    glTexCoordPointer(lua_tointeger(L, 1),
                      lua_tointeger(L, 2),
                      lua_tointeger(L, 3),
                      lua_touserdata(L, 4))
    ;
    return 0;
}
static int _luaObjC_glTexEnvf(lua_State *L)
{
    glTexEnvf(lua_tointeger(L, 1),
              lua_tointeger(L, 2),
              lua_tonumber(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexEnvfv(lua_State *L)
{
    glTexEnvfv(lua_tointeger(L, 1),
               lua_tointeger(L, 2),
               lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexEnvi(lua_State *L)
{
    glTexEnvi(lua_tointeger(L, 1),
              lua_tointeger(L, 2),
              lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexEnviv(lua_State *L)
{
    glTexEnviv(lua_tointeger(L, 1),
               lua_tointeger(L, 2),
               lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexEnvx(lua_State *L)
{
    glTexEnvx(lua_tointeger(L, 1),
              lua_tointeger(L, 2),
              lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexEnvxv(lua_State *L)
{
    glTexEnvxv(lua_tointeger(L, 1),
               lua_tointeger(L, 2),
               lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexImage2D(lua_State *L)
{
    glTexImage2D(lua_tointeger(L, 1),
                 lua_tointeger(L, 2),
                 lua_tointeger(L, 3),
                 lua_tointeger(L, 4),
                 lua_tointeger(L, 5),
                 lua_tointeger(L, 6),
                 lua_tointeger(L, 7),
                 lua_tointeger(L, 8),
                 lua_touserdata(L, 9))
    ;
    return 0;
}
static int _luaObjC_glTexParameterf(lua_State *L)
{
    glTexParameterf(lua_tointeger(L, 1),
                    lua_tointeger(L, 2),
                    lua_tonumber(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexParameterfv(lua_State *L)
{
    glTexParameterfv(lua_tointeger(L, 1),
                     lua_tointeger(L, 2),
                     lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexParameteri(lua_State *L)
{
    glTexParameteri(lua_tointeger(L, 1),
                    lua_tointeger(L, 2),
                    lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexParameteriv(lua_State *L)
{
    glTexParameteriv(lua_tointeger(L, 1),
                     lua_tointeger(L, 2),
                     lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexParameterx(lua_State *L)
{
    glTexParameterx(lua_tointeger(L, 1),
                    lua_tointeger(L, 2),
                    lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexParameterxv(lua_State *L)
{
    glTexParameterxv(lua_tointeger(L, 1),
                     lua_tointeger(L, 2),
                     lua_touserdata(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTexSubImage2D(lua_State *L)
{
    glTexSubImage2D(lua_tointeger(L, 1),
                    lua_tointeger(L, 2),
                    lua_tointeger(L, 3),
                    lua_tointeger(L, 4),
                    lua_tointeger(L, 5),
                    lua_tointeger(L, 6),
                    lua_tointeger(L, 7),
                    lua_tointeger(L, 8),
                    lua_touserdata(L, 9))
    ;
    return 0;
}
static int _luaObjC_glTranslatef(lua_State *L)
{
    glTranslatef(lua_tonumber(L, 1),
                 lua_tonumber(L, 2),
                 lua_tonumber(L, 3))
    ;
    return 0;
}
static int _luaObjC_glTranslatex(lua_State *L)
{
    glTranslatex(lua_tointeger(L, 1),
                 lua_tointeger(L, 2),
                 lua_tointeger(L, 3))
    ;
    return 0;
}
static int _luaObjC_glUnmapBufferOES(lua_State *L)
{
    lua_pushinteger(L, glUnmapBufferOES(lua_tointeger(L, 1))
                    );
    return 1;
}
static int _luaObjC_glVertexPointer(lua_State *L)
{
    glVertexPointer(lua_tointeger(L, 1),
                    lua_tointeger(L, 2),
                    lua_tointeger(L, 3),
                    lua_touserdata(L, 4))
    ;
    return 0;
}
static int _luaObjC_glViewport(lua_State *L)
{
    glViewport(lua_tointeger(L, 1),
               lua_tointeger(L, 2),
               lua_tointeger(L, 3),
               lua_tointeger(L, 4))
    ;
    return 0;
}
static int _luaObjC_glWeightPointerOES(lua_State *L)
{
    glWeightPointerOES(lua_tointeger(L, 1),
                       lua_tointeger(L, 2),
                       lua_tointeger(L, 3),
                       lua_touserdata(L, 4))
    ;
    return 0;
}

static const luaL_Reg __luaObjC_OpenGLES_Functions[]=
{
    {"glActiveTexture", _luaObjC_glActiveTexture},
    {"glAlphaFunc", _luaObjC_glAlphaFunc},
    {"glAlphaFuncx", _luaObjC_glAlphaFuncx},
    {"glBindBuffer", _luaObjC_glBindBuffer},
    {"glBindFramebufferOES", _luaObjC_glBindFramebufferOES},
    {"glBindRenderbufferOES", _luaObjC_glBindRenderbufferOES},
    {"glBindTexture", _luaObjC_glBindTexture},
    {"glBlendEquationOES", _luaObjC_glBlendEquationOES},
    {"glBlendFunc", _luaObjC_glBlendFunc},
    {"glBufferData", _luaObjC_glBufferData},
    {"glBufferSubData", _luaObjC_glBufferSubData},
    {"glCheckFramebufferStatusOES", _luaObjC_glCheckFramebufferStatusOES},
    {"glClear", _luaObjC_glClear},
    {"glClearColor", _luaObjC_glClearColor},
    {"glClearColorx", _luaObjC_glClearColorx},
    {"glClearDepthf", _luaObjC_glClearDepthf},
    {"glClearDepthx", _luaObjC_glClearDepthx},
    {"glClearStencil", _luaObjC_glClearStencil},
    {"glClientActiveTexture", _luaObjC_glClientActiveTexture},
    {"glClipPlanef", _luaObjC_glClipPlanef},
    {"glClipPlanex", _luaObjC_glClipPlanex},
    {"glColor4f", _luaObjC_glColor4f},
    {"glColor4ub", _luaObjC_glColor4ub},
    {"glColor4x", _luaObjC_glColor4x},
    {"glColorMask", _luaObjC_glColorMask},
    {"glColorPointer", _luaObjC_glColorPointer},
    {"glCompressedTexImage2D", _luaObjC_glCompressedTexImage2D},
    {"glCompressedTexSubImage2D", _luaObjC_glCompressedTexSubImage2D},
    {"glCopyTexImage2D", _luaObjC_glCopyTexImage2D},
    {"glCopyTexSubImage2D", _luaObjC_glCopyTexSubImage2D},
    {"glCullFace", _luaObjC_glCullFace},
    {"glCurrentPaletteMatrixOES", _luaObjC_glCurrentPaletteMatrixOES},
    {"glDeleteBuffers", _luaObjC_glDeleteBuffers},
    {"glDeleteFramebuffersOES", _luaObjC_glDeleteFramebuffersOES},
    {"glDeleteRenderbuffersOES", _luaObjC_glDeleteRenderbuffersOES},
    {"glDeleteTextures", _luaObjC_glDeleteTextures},
    {"glDepthFunc", _luaObjC_glDepthFunc},
    {"glDepthMask", _luaObjC_glDepthMask},
    {"glDepthRangef", _luaObjC_glDepthRangef},
    {"glDepthRangex", _luaObjC_glDepthRangex},
    {"glDisable", _luaObjC_glDisable},
    {"glDisableClientState", _luaObjC_glDisableClientState},
    {"glDrawArrays", _luaObjC_glDrawArrays},
    {"glDrawElements", _luaObjC_glDrawElements},
    {"glDrawTexfOES", _luaObjC_glDrawTexfOES},
    {"glDrawTexfvOES", _luaObjC_glDrawTexfvOES},
    {"glDrawTexiOES", _luaObjC_glDrawTexiOES},
    {"glDrawTexivOES", _luaObjC_glDrawTexivOES},
    {"glDrawTexsOES", _luaObjC_glDrawTexsOES},
    {"glDrawTexsvOES", _luaObjC_glDrawTexsvOES},
    {"glDrawTexxOES", _luaObjC_glDrawTexxOES},
    {"glDrawTexxvOES", _luaObjC_glDrawTexxvOES},
    {"glEnable", _luaObjC_glEnable},
    {"glEnableClientState", _luaObjC_glEnableClientState},
    {"glFinish", _luaObjC_glFinish},
    {"glFlush", _luaObjC_glFlush},
    {"glFogf", _luaObjC_glFogf},
    {"glFogfv", _luaObjC_glFogfv},
    {"glFogx", _luaObjC_glFogx},
    {"glFogxv", _luaObjC_glFogxv},
    {"glFramebufferRenderbufferOES", _luaObjC_glFramebufferRenderbufferOES},
    {"glFramebufferTexture2DOES", _luaObjC_glFramebufferTexture2DOES},
    {"glFrontFace", _luaObjC_glFrontFace},
    {"glFrustumf", _luaObjC_glFrustumf},
    {"glFrustumx", _luaObjC_glFrustumx},
    {"glGenBuffers", _luaObjC_glGenBuffers},
    {"glGenFramebuffersOES", _luaObjC_glGenFramebuffersOES},
    {"glGenRenderbuffersOES", _luaObjC_glGenRenderbuffersOES},
    {"glGenTextures", _luaObjC_glGenTextures},
    {"glGenerateMipmapOES", _luaObjC_glGenerateMipmapOES},
    {"glGetBooleanv", _luaObjC_glGetBooleanv},
    {"glGetBufferParameteriv", _luaObjC_glGetBufferParameteriv},
    {"glGetBufferPointervOES", _luaObjC_glGetBufferPointervOES},
    {"glGetClipPlanef", _luaObjC_glGetClipPlanef},
    {"glGetClipPlanex", _luaObjC_glGetClipPlanex},
    {"glGetError", _luaObjC_glGetError},
    {"glGetFixedv", _luaObjC_glGetFixedv},
    {"glGetFloatv", _luaObjC_glGetFloatv},
    {"glGetFramebufferAttachmentParameterivOES", _luaObjC_glGetFramebufferAttachmentParameterivOES},
    {"glGetIntegerv", _luaObjC_glGetIntegerv},
    {"glGetLightfv", _luaObjC_glGetLightfv},
    {"glGetLightxv", _luaObjC_glGetLightxv},
    {"glGetMaterialfv", _luaObjC_glGetMaterialfv},
    {"glGetMaterialxv", _luaObjC_glGetMaterialxv},
    {"glGetPointerv", _luaObjC_glGetPointerv},
    {"glGetRenderbufferParameterivOES", _luaObjC_glGetRenderbufferParameterivOES},
    {"glGetString", _luaObjC_glGetString},
    {"glGetTexEnvfv", _luaObjC_glGetTexEnvfv},
    {"glGetTexEnviv", _luaObjC_glGetTexEnviv},
    {"glGetTexEnvxv", _luaObjC_glGetTexEnvxv},
    {"glGetTexParameterfv", _luaObjC_glGetTexParameterfv},
    {"glGetTexParameteriv", _luaObjC_glGetTexParameteriv},
    {"glGetTexParameterxv", _luaObjC_glGetTexParameterxv},
    {"glHint", _luaObjC_glHint},
    {"glIsBuffer", _luaObjC_glIsBuffer},
    {"glIsEnabled", _luaObjC_glIsEnabled},
    {"glIsFramebufferOES", _luaObjC_glIsFramebufferOES},
    {"glIsProgram", _luaObjC_glIsProgram},
    {"glIsRenderbufferOES", _luaObjC_glIsRenderbufferOES},
    {"glIsTexture", _luaObjC_glIsTexture},
    {"glLightModelf", _luaObjC_glLightModelf},
    {"glLightModelfv", _luaObjC_glLightModelfv},
    {"glLightModelx", _luaObjC_glLightModelx},
    {"glLightModelxv", _luaObjC_glLightModelxv},
    {"glLightf", _luaObjC_glLightf},
    {"glLightfv", _luaObjC_glLightfv},
    {"glLightx", _luaObjC_glLightx},
    {"glLightxv", _luaObjC_glLightxv},
    {"glLineWidth", _luaObjC_glLineWidth},
    {"glLineWidthx", _luaObjC_glLineWidthx},
    {"glLoadIdentity", _luaObjC_glLoadIdentity},
    {"glLoadMatrixf", _luaObjC_glLoadMatrixf},
    {"glLoadMatrixx", _luaObjC_glLoadMatrixx},
    {"glLoadPaletteFromModelViewMatrixOES", _luaObjC_glLoadPaletteFromModelViewMatrixOES},
    {"glLogicOp", _luaObjC_glLogicOp},
    {"glMapBufferOES", _luaObjC_glMapBufferOES},
    {"glMaterialf", _luaObjC_glMaterialf},
    {"glMaterialfv", _luaObjC_glMaterialfv},
    {"glMaterialx", _luaObjC_glMaterialx},
    {"glMaterialxv", _luaObjC_glMaterialxv},
    {"glMatrixIndexPointerOES", _luaObjC_glMatrixIndexPointerOES},
    {"glMatrixMode", _luaObjC_glMatrixMode},
    {"glMultMatrixf", _luaObjC_glMultMatrixf},
    {"glMultMatrixx", _luaObjC_glMultMatrixx},
    {"glMultiTexCoord4f", _luaObjC_glMultiTexCoord4f},
    {"glMultiTexCoord4x", _luaObjC_glMultiTexCoord4x},
    {"glNormal3f", _luaObjC_glNormal3f},
    {"glNormal3x", _luaObjC_glNormal3x},
    {"glNormalPointer", _luaObjC_glNormalPointer},
    {"glOrthof", _luaObjC_glOrthof},
    {"glOrthox", _luaObjC_glOrthox},
    {"glPixelStorei", _luaObjC_glPixelStorei},
    {"glPointParameterf", _luaObjC_glPointParameterf},
    {"glPointParameterfv", _luaObjC_glPointParameterfv},
    {"glPointParameterx", _luaObjC_glPointParameterx},
    {"glPointParameterxv", _luaObjC_glPointParameterxv},
    {"glPointSize", _luaObjC_glPointSize},
    {"glPointSizePointerOES", _luaObjC_glPointSizePointerOES},
    {"glPointSizex", _luaObjC_glPointSizex},
    {"glPolygonOffset", _luaObjC_glPolygonOffset},
    {"glPolygonOffsetx", _luaObjC_glPolygonOffsetx},
    {"glPopMatrix", _luaObjC_glPopMatrix},
    {"glPushMatrix", _luaObjC_glPushMatrix},
    {"glReadPixels", _luaObjC_glReadPixels},
    {"glRenderbufferStorageOES", _luaObjC_glRenderbufferStorageOES},
    {"glRotatef", _luaObjC_glRotatef},
    {"glRotatex", _luaObjC_glRotatex},
    {"glSampleCoverage", _luaObjC_glSampleCoverage},
    {"glSampleCoveragex", _luaObjC_glSampleCoveragex},
    {"glScalef", _luaObjC_glScalef},
    {"glScalex", _luaObjC_glScalex},
    {"glScissor", _luaObjC_glScissor},
    {"glShadeModel", _luaObjC_glShadeModel},
    {"glStencilFunc", _luaObjC_glStencilFunc},
    {"glStencilMask", _luaObjC_glStencilMask},
    {"glStencilOp", _luaObjC_glStencilOp},
    {"glTexCoordPointer", _luaObjC_glTexCoordPointer},
    {"glTexEnvf", _luaObjC_glTexEnvf},
    {"glTexEnvfv", _luaObjC_glTexEnvfv},
    {"glTexEnvi", _luaObjC_glTexEnvi},
    {"glTexEnviv", _luaObjC_glTexEnviv},
    {"glTexEnvx", _luaObjC_glTexEnvx},
    {"glTexEnvxv", _luaObjC_glTexEnvxv},
    {"glTexImage2D", _luaObjC_glTexImage2D},
    {"glTexParameterf", _luaObjC_glTexParameterf},
    {"glTexParameterfv", _luaObjC_glTexParameterfv},
    {"glTexParameteri", _luaObjC_glTexParameteri},
    {"glTexParameteriv", _luaObjC_glTexParameteriv},
    {"glTexParameterx", _luaObjC_glTexParameterx},
    {"glTexParameterxv", _luaObjC_glTexParameterxv},
    {"glTexSubImage2D", _luaObjC_glTexSubImage2D},
    {"glTranslatef", _luaObjC_glTranslatef},
    {"glTranslatex", _luaObjC_glTranslatex},
    {"glUnmapBufferOES", _luaObjC_glUnmapBufferOES},
    {"glVertexPointer", _luaObjC_glVertexPointer},
    {"glViewport", _luaObjC_glViewport},
    {"glWeightPointerOES", _luaObjC_glWeightPointerOES},
    {NULL, NULL},
};

int LuaOpenGLES(lua_State *L)
{
    luaObjC_loadGlobalConstants(L, __luaObjCOpenGLESConstants);
    return 0;
}
